- id: semantic-merge
  name: Semantic Merge
  description: AI-powered semantic merging of documentation files
  entry: python -m sem_merge
  language: python
  files: \.(md|rst|txt|adoc|asciidoc)$
  pass_filenames: true
  require_serial: false
  minimum_pre_commit_version: "2.9.0"
  stages: [pre-commit] 