-   id: semantic-merge
    name: Semantic Document Merge
    description: 'Semantically merge documentation files with remote main branch using DeepSeek'
    entry: python -m sem_merge
    language: python
    files: \.(md|mdc)$
    exclude_types: [binary]
    require_serial: false
    minimum_pre_commit_version: '2.15.0'
    pass_filenames: true
    stages: [pre-commit] 